### ISSUE TITLE
Could you write some instructions on how to install this project on Windows?

### ISSUE THREAD

**Issue by bit-scientist** [chizhanyuefeng/fall_down_detection#21]
Thank you for this repo, but could you give some clear step by step instructions in readme chapter so that others could reach what you did

**Comment by chizhanyuefeng** [comment]
ok, I will update readme few weeks, and our paper is being published

**Comment by bit-scientist** [comment]
hi @chizhanyuefeng , Can you link the address of your paper if it is archived online? Thanks

**Comment by chizhanyuefeng** [comment]
@bit-scientist Our paper is under review, so I cant open it.But this week I will update readme
