### ISSUE TITLE
关于输入数据类型

### ISSUE THREAD

**Issue by 363325971** [chizhanyuefeng/fall_down_detection#23]
你好，我想请教下该项目输入的数据是什么传感器的数据，能否直接使用摄像头的视频做检测呢？

**Comment by chizhanyuefeng** [comment]
三轴加速度传感器和三轴陀螺仪传感器，不能使用视频做检测

**Comment by xwr96** [comment]
你好！我想问如果要实时的话可以用哪些作为输入呢？传感器的话用手机还是？
